name: Rust

on:
  push:
    branches:
     - main
    tags:
     - "*"
  pull_request:
    branches:
     - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-20.04,   target: x86_64-unknown-linux-gnu,   platform: linux-x64    }
          - { os: ubuntu-20.04,   target: aarch64-unknown-linux-gnu,  platform: linux-arm64  }
          - { os: ubuntu-20.04,   target: x86_64-unknown-linux-musl,  platform: linux-musl   }
          - { os: ubuntu-20.04,   target: x86_64-unknown-freebsd,     platform: linux-bsd    }
          - { os: macos-latest,   target: x86_64-apple-darwin,        platform: darwin-x64   }
          - { os: macos-latest,   target: aarch64-apple-darwin,       platform: darwin-arm64 }
          - { os: windows-latest, target: x86_64-pc-windows-msvc,     platform: win32-x64    }
          - { os: windows-latest, target: i686-pc-windows-msvc,       platform: win32-ia32   }
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install aarch64-linux-gnu
        if: ${{ matrix.platform == 'linux-arm64'}}
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }} --target-dir target/${{ matrix.platform }}
        

